version: '3.7'

services:

  users:
    build:
      context: ./services/users
      dockerfile: Dockerfile
    volumes:
      - './services/users:/usr/src/app'
    ports:
      - 5001:5000
    environment:
      - FLASK_ENV=development
      - APP_SETTINGS=project.config.TestingConfig

      #check
      - DATASTORE_EMULATOR_HOST=datastore:8001
      - DATASTORE_PROJECT_ID=project-test
    depends_on:
      - datastore

  datastore:
    build:
      context: ./services/users/project/db
      dockerfile: Dockerfile
    command: ["--no-store-on-disk", "--consistency=1.0"]
    environment:
      - DATASTORE_PROJECT_ID=project-test
      - DATASTORE_LISTEN_ADDRESS=0.0.0.0:8001
    ports:
      - "8001:8001"